# Tensor

Tensors are similar to NumPy's ndarray, with the addition being that Tensors can also be used on a **GPU** to accelerate computing.

In [1]:
from __future__ import print_function
import torch

In [2]:
x = torch.empty(5, 3)
print(x)

tensor([[1.8174e+31, 1.9519e-19, 7.3909e+22],
        [7.1377e+31, 5.3740e+19, 7.3909e+22],
        [4.5581e+30, 5.2806e-04, 4.8419e+30],
        [7.1832e+22, 1.9007e-19, 1.8888e+31],
        [1.2123e+25, 4.6114e+24, 1.7237e+25]])


In [3]:
x = torch.rand(5, 3)
print(x)

tensor([[0.3191, 0.1403, 0.9310],
        [0.2549, 0.0632, 0.4521],
        [0.6451, 0.6665, 0.4617],
        [0.0603, 0.2691, 0.5422],
        [0.4380, 0.6286, 0.2785]])


In [4]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [5]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


In [6]:
x = x.new_ones(5, 3, dtype=torch.double)      # new_* methods take in sizes
print(x)

x = torch.randn_like(x, dtype=torch.float)    # override dtype!
print(x)                                      # result has the same size


tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[ 0.1281,  1.4938,  0.5504],
        [-0.1832,  0.6597, -0.1345],
        [-0.8611,  0.5951, -0.1862],
        [-0.7094, -1.5887,  1.7565],
        [-0.7789,  2.5385, -1.2190]])


In [7]:
print(x.size())

torch.Size([5, 3])


In [8]:
y = torch.rand(5, 3)
print(x + y)

tensor([[ 0.4965,  1.5773,  1.3570],
        [ 0.6775,  0.8395,  0.7226],
        [-0.6880,  1.2545,  0.1379],
        [-0.5703, -1.0212,  1.9891],
        [-0.6707,  3.0683, -0.8624]])


In [9]:
print(torch.add(x, y))

tensor([[ 0.4965,  1.5773,  1.3570],
        [ 0.6775,  0.8395,  0.7226],
        [-0.6880,  1.2545,  0.1379],
        [-0.5703, -1.0212,  1.9891],
        [-0.6707,  3.0683, -0.8624]])


In [10]:
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[ 0.4965,  1.5773,  1.3570],
        [ 0.6775,  0.8395,  0.7226],
        [-0.6880,  1.2545,  0.1379],
        [-0.5703, -1.0212,  1.9891],
        [-0.6707,  3.0683, -0.8624]])


In [11]:
# adds x to y
y.add_(x)
print(y)

tensor([[ 0.4965,  1.5773,  1.3570],
        [ 0.6775,  0.8395,  0.7226],
        [-0.6880,  1.2545,  0.1379],
        [-0.5703, -1.0212,  1.9891],
        [-0.6707,  3.0683, -0.8624]])


In [12]:
print(x[:, 1])

tensor([ 1.4938,  0.6597,  0.5951, -1.5887,  2.5385])


In [13]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)  # the size -1 is inferred from other dimensions
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


If you have a one element tensor, use `.item()` to get the value as a Python number

In [14]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([-1.9023])
-1.9022501707077026


# NumPy Bridge

Converting a Torch Tensor to a NumPy array and vice versa is a breeze.

The Torch Tensor and NumPy array will share their underlying memory locations (**if the Torch Tensor is on CPU**), and changing one will change the other.

All the Tensors on the CPU except a CharTensor support converting to NumPy and back.

In [15]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [16]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


In [17]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [18]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


# CUDA Tensors

Tensors can be moved onto any device using the `.to` method.

In [19]:
# let us run this cell only if CUDA is available
# We will use ``torch.device`` objects to move tensors in and out of GPU
if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA device object
    y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
    x = x.to(device)                       # or just use strings ``.to("cuda")``
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # ``.to`` can also change dtype together!

tensor([-0.9023], device='cuda:0')
tensor([-0.9023], dtype=torch.float64)
